apiVersion: v1
kind: PersistentVolume
metadata:
  name: mq-pv
  namespace: mqtt
  labels:
    type: local
    app: mosquitto
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  claimRef:
    namespace: mqtt
    name: mq-pv-claim
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mosquitto/data"
